### ISSUE TITLE
The application crashes after an interaction with the Menza at startup option

### ISSUE THREAD

**Issue by Radian-Fi** [Lastaapps/menza#13]
Appka spadne po kliknutí na "Menza po spouštění" (defaultně nastavené na "Vždy se zeptat") v "Nastavení."

Android version:    34
App version name:   1.3.0
App version code:   1030000
Phone model:        Pixel 6
Phone manufacturer: Google 
Date and Time:      2024-01-23T18:35:28.718+01:00[Europe/Prague]
Screen size:        1080 x 2209 px

App crashed
2024-01-23T17:34:28.504Z[UTC]
Vertically scrollable component was measured with an infinity maximum height constraints, which is disallowed. One of the common reasons is nesting layouts like LazyColumn and Column(Modifier.verticalScroll()). If you want to add a header before the list of items please add a header as a separate item() before the main items() inside the LazyColumn scope. There are could be other reasons for this to happen: your ComposeView was added into a LinearLayout with some weight, you applied Modifier.wrapContentSize(unbounded = true) or wrote a custom layout. Please try to remove the source of infinite constraints in the hierarchy above the scrolling container.
java.lang.IllegalStateException: Vertically scrollable component was measured with an infinity maximum height constraints, which is disallowed. One of the common reasons is nesting layouts like LazyColumn and Column(Modifier.verticalScroll()). If you want to add a header before the list of items please add a header as a separate item() before the main items() inside the LazyColumn scope. There are could be other reasons for this to happen: your ComposeView was added into a LinearLayout with some weight, you applied Modifier.wrapContentSize(unbounded = true) or wrote a custom layout. Please try to remove the source of infinite constraints in the hierarchy above the scrolling container.
	at androidx.compose.foundation.a.d(SourceFile:23)
	at x.v.m(SourceFile:47)
	at t.p0.h(SourceFile:24)
	at t.p0.m(SourceFile:639)
	at v1.d0.c(SourceFile:74)
	at x1.x.a(SourceFile:38)
	at s.l.a(SourceFile:9)
	at s.l.k(SourceFile:14)
	at v1.x.g(SourceFile:8)
	at x1.d0.a(SourceFile:11)
	at s.l.a(SourceFile:39)
	at s.l.k(SourceFile:27)
	at v1.x.g(SourceFile:8)
	at x1.d0.a(SourceFile:11)
	at i1.q0.g(SourceFile:1)
	at x1.d0.a(SourceFile:11)
	at w.g0.g(SourceFile:99)
	at x1.d0.a(SourceFile:11)
	at r.l0.b(SourceFile:34)
	at r.l0.c(SourceFile:14)
	at a1.c.F(SourceFile:60)
	at a1.a0.a(SourceFile:52)
	at a1.b0.c(SourceFile:153)
	at x1.s1.a(SourceFile:3)
	at x1.m0.r0(SourceFile:109)
	at x1.m0.a(SourceFile:96)
	at w.g1.b(SourceFile:118)
	at w.f1.c(SourceFile:32)
	at x1.x.a(SourceFile:38)
	at r.l0.b(SourceFile:34)
	at r.l0.c(SourceFile:14)
	at a1.c.F(SourceFile:60)
	at a1.a0.a(SourceFile:52)
	at a1.b0.c(SourceFile:153)
	at x1.s1.a(SourceFile:3)
	at x1.m0.r0(SourceFile:109)
	at x1.m0.a(SourceFile:96)
	at w.v.c(SourceFile:112)
	at x1.x.a(SourceFile:38)
	at s.b3.g(SourceFile:50)
	at x1.d0.a(SourceFile:11)
	at s.l.a(SourceFile:9)
	at s.l.k(SourceFile:14)
	at v1.x.g(SourceFile:8)
	at x1.d0.a(SourceFile:11)
	at s.l.a(SourceFile:39)
	at s.l.k(SourceFile:27)
	at v1.x.g(SourceFile:8)
	at x1.d0.a(SourceFile:11)
	at i1.q0.g(SourceFile:1)
	at x1.d0.a(SourceFile:11)
	at w.a1.g(SourceFile:33)
	at x1.d0.a(SourceFile:11)
	at r.l0.b(SourceFile:34)
	at r.l0.c(SourceFile:14)
	at a1.c.F(SourceFile:60)
	at a1.a0.a(SourceFile:52)
	at a1.b0.c(SourceFile:153)
	at x1.s1.a(SourceFile:3)
	at x1.m0.r0(SourceFile:109)
	at x1.m0.a(SourceFile:96)
	at w.v.c(SourceFile:112)
	at x1.x.a(SourceFile:38)
	at i1.q0.g(SourceFile:1)
	at x1.d0.a(SourceFile:11)
	at i1.q0.g(SourceFile:1)
	at x1.d0.a(SourceFile:11)
	at r.l0.b(SourceFile:34)
	at r.l0.c(SourceFile:14)
	at a1.c.F(SourceFile:60)
	at a1.a0.a(SourceFile:52)
	at a1.b0.c(SourceFile:153)
	at x1.s1.a(SourceFile:3)
	at x1.m0.r0(SourceFile:109)
	at x1.m0.a(SourceFile:96)
	at w.v.c(SourceFile:112)
	at x1.x.a(SourceFile:38)
	at w.g0.g(SourceFile:99)
	at x1.d0.a(SourceFile:11)
	at r.l0.b(SourceFile:34)
	at r.l0.c(SourceFile:14)
	at a1.c.F(SourceFile:60)
	at a1.a0.a(SourceFile:52)
	at a1.b0.c(SourceFile:153)
	at x1.s1.a(SourceFile:3)
	at x1.m0.r0(SourceFile:109)
	at x1.m0.a(SourceFile:96)
	at s2.e.c(SourceFile:150)
	at x1.x.a(SourceFile:38)
	at r.l0.b(SourceFile:34)
	at r.l0.c(SourceFile:14)
	at a1.c.F(SourceFile:60)
	at a1.a0.a(SourceFile:52)
	at a1.b0.c(SourceFile:153)
	at x1.s1.a(SourceFile:3)
	at x1.m0.r0(SourceFile:109)
	at x1.m0.a(SourceFile:96)
	at v1.d1.c(SourceFile:39)
	at x1.x.a(SourceFile:38)
	at r.l0.b(SourceFile:34)
	at r.l0.c(SourceFile:14)
	at a1.c.F(SourceFile:60)
	at a1.a0.a(SourceFile:52)
	at a1.b0.c(SourceFile:153)
	at x1.s1.a(SourceFile:3)
	at x1.m0.r0(SourceFile:109)
	at x1.u0.c(SourceFile:18)
	at x1.u0.m(SourceFile:18)
	at x1.u0.j(SourceFile:59)
	at y1.w.onMeasure(SourceFile:83)
	at android.view.View.measure(View.java:27133)
	at y1.a.e(SourceFile:64)
	at s2.n.e(SourceFile:5)
	at y1.a.onMeasure(SourceFile:4)
	at android.view.View.measure(View.java:27133)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27133)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27133)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:750)
	at android.view.View.measure(View.java:27133)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4379)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2913)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3270)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2650)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9526)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
	at android.view.Choreographer.doFrame(Choreographer.java:882)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by Lastaapps** [comment]
Ježiš, jsem debílek, díky moc. Si živě vybavuju, jak jsem dělal poslední průchod aplikací před vydáním a říkal si: "Na tohle nebudu klikat, to vždycky fungovalo". V další hodině pošlu opravu na Google review. Ještě jednou díky za rychlej report.

**Comment by Radian-Fi** [comment]
Není vůbec zač. Děláte výbornou práci na aktuálně bezesporu nejlepší mobilní aplikaci pro menzy ČVUT/VŠCHT.
