### ISSUE TITLE
Menza Strahov not working

### ISSUE THREAD

**Issue by Bertik23** [Lastaapps/menza#5]
Zde prosím popište váš problém více

Chtěl jsem se kouknout na menzu Strahov a this. Ostatní menzy fungují v pohodě a na webu taky je jídelníček v pořádku

Android version:    30
App version name:   1.2.0
App version code:   1020000
Phone model:        RMX2155
Phone manufacturer: realme 
Date and Time:      2022-09-29T14:13:13.61+02:00[Europe/Prague]
Screen size:        1080 x 2153 px

"Internal app problem"
2022-09-29T14:13:13.612
For input string: "3.9.10"
java.lang.NumberFormatException: For input string: "3.9.10"
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.lang.Integer.parseInt(Integer.java:650)
	at h8.v0.T(SourceFile:12)
	at androidx.activity.result.d.q(Unknown Source:9)
	at h8.q0.A(SourceFile:2)
	at h8.x0.T(SourceFile:13)
	at h8.q0.h(SourceFile:4)
	at h8.q0.z(SourceFile:2)
	at h8.b1$a.T(SourceFile:9)
	at androidx.window.layout.e.p(SourceFile:64)
	at h8.b1.d(Unknown Source:7)
	at j8.h0$b.i(SourceFile:31)
	at ma.a.K(SourceFile:3)
	at db.l0.run(SourceFile:18)
	at ib.h.run(SourceFile:2)
	at jb.j.run(SourceFile:1)
	at jb.a$a.run(SourceFile:14)

**Comment by Lastaapps** [comment]
Ahoj, aktualizuj na včera vydanou verzi prosim, tam je to ošéfený. Způsobuje to, že nějaký génius napsal alergeny oddělené tečkou místo čárky, mezery, čárky s tečkou... a starší verze to neumí parsovat.
Každopádně díky moc za report ❤️
