### ISSUE TITLE
Nelze načíst dnešní jídelníček studentské menzy

### ISSUE THREAD

**Issue by vojta-horanek** [Lastaapps/menza#6]
Android version:    31
App version name:   1.2.2
App version code:   1020200
Phone model:        moto g(60)
Phone manufacturer: motorola 
Date and Time:      2022-11-04T10:26:32.387+01:00[Europe/Prague]
Screen size:        1080 x 2285 px

"Internal app problem"
2022-11-04T10:26:32.388
empty String
java.lang.NumberFormatException: empty String
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
	at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:543)
	at g8.o1.a(SourceFile:39)
	at g8.j1.V(SourceFile:229)
	at c0.c.q(SourceFile:31)
	at c0.c.X(SourceFile:10)
	at g8.m1$a.V(SourceFile:87)
	at z.w0.S(SourceFile:233)
	at g8.m1.e(Unknown Source:7)
	at i8.n1$b.j(SourceFile:192)
	at da.a.u(SourceFile:9)
	at xa.n0.run(SourceFile:107)
	at cb.f.run(SourceFile:13)
	at db.j.run(SourceFile:3)
	at db.a$a.run(SourceFile:82)

**Comment by Lastaapps** [comment]
![SmartSelect_20221104_103626_Opera.jpg](https://user-images.githubusercontent.com/47794319/199941151-f9e253b9-1923-4095-b31e-70a761529acd.jpg)

Ach jo, další edge case 🙃
Dík za report

**Comment by Lastaapps** [comment]
Novej release tohle fixuje, díky
