### ISSUE TITLE
empty String error report

### ISSUE THREAD

**Issue by strnalad** [Lastaapps/menza#7]
Aplikace hází empty String error při pokusu o zobrazení jídel ze Studentského Domu. 

Android version:    31
App version name:   1.2.2
App version code:   1020200
Date and Time:      2022-11-11T12:04:14.16+01:00[Europe/Prague]
Screen size:        1080 x 2069 px

"Internal app problem"
2022-11-11T12:04:14.162
empty String
java.lang.NumberFormatException: empty String
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at g8.o1.a(SourceFile:39)
	at g8.j1.V(SourceFile:229)
	at c0.c.q(SourceFile:31)
	at c0.c.X(SourceFile:10)
	at g8.m1$a.V(SourceFile:87)
	at z.w0.S(SourceFile:233)
	at g8.m1.e(Unknown Source:7)
	at i8.n1$b.j(SourceFile:192)
	at da.a.u(SourceFile:9)
	at xa.n0.run(SourceFile:107)
	at cb.f.run(SourceFile:13)
	at db.j.run(SourceFile:3)
	at db.a$a.run(SourceFile:82)

**Comment by Lastaapps** [comment]
Ahoj, díky za report, vim o tom, až seženu trochu času, tak to nějak fixnu. Způsobuje to, že cenu napsali do jména jídla a ne do sloupce pro číslo a nenapadlo mě, že by mohla být jídla bez ceny 😅 Ještě jednou dík

**Comment by Lastaapps** [comment]
Novej release tohle fixuje, díky
