### ISSUE TITLE
Scraping Opening hours

### ISSUE THREAD

**Issue by fulopjoz** [Lastaapps/menza#9]

**Comment by Lastaapps** [comment]
Nazdar, díky za report, po dovolený na to kouknu. Kdy se ti to stalo/co jsi dělal? Případně jaká menza? Díky

**Comment by Lastaapps** [comment]
Jen si to tu dovolím přepsati
```
Zde prosím popište váš problém více
Android version: 33
App version name: 1.2.6
App version code: 1020600
Phone model: SM-M135F
Phone manufacturer: samsung
Date and Time: 2023-08-08T08:45:41.566+02:00[Europe/Prague]
Screen size: 1080 x 2303 px
"Internal app problem"
2023-08-08T08:45:41.569
fromIndex = -1 java.lang.IndexOutOfBoundsException: fromIndex = -1
at java.util.AbstractList.subListRangeCheck(AbstractList.java:505)
at java.util.AbstractList.subList(AbstractList.java:497)
at n8.p0.e0(SourceFile:170)
at c0.b.j(SourceFile:35)
at n8.r0.e0(SourceFile:29)
at c0.b.j(SourceFile:35)
at n8.s0.e0(SourceFile:35)
at c0.b.f(SourceFile:31)
at n8.t0$a.e0(SourceFile:34)
at a1.c.Z(SourceFile:229)
at n8.t0.e(Unknown Source:7)
at p8.j1.m(SourceFile:136)
at z9.a.p(SourceFile:9)
at sa.m0.run(SourceFile:107)
at xa.f.run(SourceFile:13)
at ya.j.run(SourceFile:3)
at ya.a$a.run(SourceFile:82)
```

```
at java.util.AbstractList.subListRangeCheck(AbstractList.java:505)
at java.util.AbstractList.subList(AbstractList.java:497)
at cz.lastaapps.scraping.OpeningHoursScraperImpl$parseHtml$1$1$1$1.invoke(OpeningHoursScraperImpl.kt:69)
at cz.lastaapps.scraping.OpeningHoursScraperImpl$parseHtml$1$1$1$1.invoke(OpeningHoursScraperImpl.kt:52)
at cz.lastaapps.scraping.ScrapeUtilsKt$findAllAndCycle$1.invoke(ScrapeUtils.kt:85)
at cz.lastaapps.scraping.ScrapeUtilsKt$findAllAndCycle$1.invoke(ScrapeUtils.kt:82)
at it.skrape.selects.CssSelectable.findAll(CssSelectable.java:98)
at cz.lastaapps.scraping.ScrapeUtilsKt.findAllAndCycle(ScrapeUtils.kt:82)
at cz.lastaapps.scraping.ScrapeUtilsKt.tryFindAllAndCycle(ScrapeUtils.kt:75)
at cz.lastaapps.scraping.OpeningHoursScraperImpl$parseHtml$1$1$1.invoke(OpeningHoursScraperImpl.kt:52)
at cz.lastaapps.scraping.OpeningHoursScraperImpl$parseHtml$1$1$1.invoke(OpeningHoursScraperImpl.kt:48)
at cz.lastaapps.scraping.ScrapeUtilsKt$findAllAndCycle$1.invoke(ScrapeUtils.kt:85)
at cz.lastaapps.scraping.ScrapeUtilsKt$findAllAndCycle$1.invoke(ScrapeUtils.kt:82)
at it.skrape.selects.CssSelectable.findAll(CssSelectable.java:98)
at cz.lastaapps.scraping.ScrapeUtilsKt.findAllAndCycle(ScrapeUtils.kt:82)
at cz.lastaapps.scraping.ScrapeUtilsKt.tryFindAllAndCycle(ScrapeUtils.kt:75)
at cz.lastaapps.scraping.OpeningHoursScraperImpl$parseHtml$1$1.invoke(OpeningHoursScraperImpl.kt:48)
at cz.lastaapps.scraping.OpeningHoursScraperImpl$parseHtml$1$1.invoke(OpeningHoursScraperImpl.kt:44)
at cz.lastaapps.scraping.ScrapeUtilsKt$findAllAndCycle$1.invoke(ScrapeUtils.kt:85)
at cz.lastaapps.scraping.ScrapeUtilsKt$findAllAndCycle$1.invoke(ScrapeUtils.kt:82)
at it.skrape.selects.CssSelectable.findAll(CssSelectable.java:98)
at cz.lastaapps.scraping.ScrapeUtilsKt.findAllAndCycle(ScrapeUtils.kt:82)
at cz.lastaapps.scraping.OpeningHoursScraperImpl$parseHtml$1.invoke(OpeningHoursScraperImpl.java:44)
at cz.lastaapps.scraping.OpeningHoursScraperImpl$parseHtml$1.invoke(OpeningHoursScraperImpl.java:43)
at it.skrape.selects.CssSelectable.findFirst(CssSelectable.java:120)
at cz.lastaapps.scraping.OpeningHoursScraperImpl.parseHtml(OpeningHoursScraperImpl.kt:43)
at cz.lastaapps.scraping.OpeningHoursScraperImpl.access$parseHtml(OpeningHoursScraperImpl.kt:31)
at cz.lastaapps.scraping.OpeningHoursScraperImpl$scrape$1.invoke(OpeningHoursScraperImpl.kt:37)
at cz.lastaapps.scraping.OpeningHoursScraperImpl$scrape$1.invoke(OpeningHoursScraperImpl.kt:37)
at it.skrape.core.ParserKt.htmlDocument(Parser.kt:59)
at it.skrape.core.ParserKt.htmlDocument$default(Parser.kt:53)
at cz.lastaapps.scraping.OpeningHoursScraperImpl.scrape(OpeningHoursScraperImpl.kt:37)
at cz.lastaapps.storage.repo.OpeningHoursRepoImpl$refreshInternal$2.invokeSuspend(OpeningHoursRepoImpl.kt:99)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by Lastaapps** [comment]
@fulopjoz Díky, mám to opraveno, v pondělí to vydám.
